baseURL = 'https://takuto-na.github.io/my-work-toolbox/'
languageCode = 'ja'
title = 'My Work Toolbox'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowBreadCrumbs = true

[menu]
  [[menu.main]]
    identifier = "tools"
    name = "Tools"
    url = "/tools/"
    weight = 10